---
- name: Docker - Dependencies
  tags: docker
  become: true
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: latest
    update_cache: yes

- name: Docker - GPG key
  tags: docker
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker.gpg
    state: present

- name: Docker - Get architecture
  tags: docker
  shell: dpkg --print-architecture
  register: architecture

- name: Docker - Repository
  tags: docker
  become: true
  apt_repository:
    repo: deb [arch={{ architecture.stdout }} signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present

- name: Docker - Installation
  tags: docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: latest
    update_cache: yes

- name: Docker - Check Started
  tags: docker
  become: true
  service:
    name: docker
    state: started
    enabled: yes

- name: Docker - Get user
  tags: docker
  shell: "echo -n {{ ansible_env.USER }}"
  register: my_linux_login

- name: Docker - User to docker group
  tags: docker
  become: true
  user:
    name: "{{ my_linux_login.stdout }}"
    groups: docker
    append: yes
  notify: "Docker - Restart"
  # Restart computer if you want to call docker without sudo
